# Shallow and Deep Copies

These problems will cover the concepts touched on in <a href="../lectures/Shallow and Deep Copies.ipynb">Shallow and Deep Copies</a>.

1. Look at the code below, what should happen when it is executed?

When you change the 4th entry of `b` the 4th entry of `a` is also changed, because you only performed an assignment.

In [1]:
a = [1,2,3,4,5,6]
b = a
b[3] = 71

print(a)
print(b)

[1, 2, 3, 71, 5, 6]
[1, 2, 3, 71, 5, 6]


2. What would you need to change so that `a` is not changed when you change `b`?

In [2]:
import copy

In [3]:
## code or write here
a = [1,2,3,4,5,6]

## use copy.copy(a)
b = copy.copy(a)
b[3] = 71

print(a)
print(b)


[1, 2, 3, 4, 5, 6]
[1, 2, 3, 71, 5, 6]


3. What should happen when the below code is executed?

`a` will look like `b` because we only performed a shallow copy of `a`.

In [4]:
a = [[1, 2, 3, 4], 
     [5, 6, 7, 8]]

b = copy.copy(a)
b[0][2] = 71

a

[[1, 2, 71, 4], [5, 6, 7, 8]]

4. Rewrite the code from 3. so that `a` is not affected when we change `b`.

In [5]:
a = [[1, 2, 3, 4], 
     [5, 6, 7, 8]]

b = copy.deepcopy(a)
b[0][2] = 71

a

[[1, 2, 3, 4], [5, 6, 7, 8]]

5. What will happen when the following code chunks are run?

Because you only performed an assignment when you change `b` you will also change `a`.

In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
b = a

b[2] = 1

print(a)
print(b)

[1 2 1 4]
[1 2 1 4]


6. Try running `b = a.copy()` and see if the issue from problem 5. persists.

In [8]:
## Code here

## it is the same :)
## just add a .copy()

a = np.array([1,2,3,4])
b = a.copy()

b[2] = 1

print(a)
print(b)


[1 2 3 4]
[1 2 1 4]


7. Delete `a` and `b`.

In [9]:
## code here
del a,b



8. In the code below we will create a `pandas` `DataFrame` and store it in the variable `df`. Try running `df_copy = df.copy()` what happens when you try and execute the final code chunk? Is the original `df` altered?

In [10]:
import pandas as pd

df = pd.DataFrame({'column_1':[435, 999, 545],
                      'column_2':["ab", "bc", "de"],
                      'column_3':[True, True, False]})

In [11]:
## code here

## .copy() to the rescue again!
df_copy = df.copy()


In [12]:
df_copy.loc[2, 'column_2'] = "cd"

print("df = ")
print(df)

print()

print("df_copy = ")
print(df_copy)

df = 
   column_1 column_2  column_3
0       435       ab      True
1       999       bc      True
2       545       de     False

df_copy = 
   column_1 column_2  column_3
0       435       ab      True
1       999       bc      True
2       545       cd     False


--------------------------

This notebook was written for the Erd&#337;s Institute C&#337;de Data Science Boot Camp by Matthew Osborne, Ph. D., 2023.

Any potential redistributors must seek and receive permission from Matthew Tyler Osborne, Ph.D. prior to redistribution. Redistribution of the material contained in this repository is conditional on acknowledgement of Matthew Tyler Osborne, Ph.D.'s original authorship and sponsorship of the Erdős Institute as subject to the license (see License.md)